### ISSUE TITLE
problem with doc.check() 

### ISSUE THREAD

**Issue by elgow** [fellowinsights/prosemirror-py#40]
One of the primary reasons that I want to use prosemirror-py is so that I can check the validity of documents that are manipulated on the server side to avoid having them fail in the javascript version of the editor in the browser. The critical function for this, doc.check(), seems to have a problem.  Given a valid set of  schema nodes in variable schema_json and a valid document in doc_json,

```
from prosemirror.model import Node, Schema
spec = dict(nodes=json.loads(schema_json), marks={})
sch = Schema(spec)
doc_node = Node.from_json(sch, doc_json)
doc_node.check()
```

This gets the following

```
In [47]: doc_node.check()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-3ea5ce72dda7> in <module>
----> 1 doc_node.check()

~/.pyenv/versions/odoo11/lib/python3.6/site-packages/prosemirror/model/node.py in check(self)
    240                 f"Invalid content for node {self.type.name}: {str(self.content)[:50]}"
    241             )
--> 242         return self.content.for_each(lambda node: node.check())
    243
    244     def to_json(self):

~/.pyenv/versions/odoo11/lib/python3.6/site-packages/prosemirror/model/fragment.py in for_each(self, f)
    161         while i < len(self.content):
    162             child = self.content[i]
--> 163             f(child, p, i)
    164             p += child.node_size
    165             i += 1

TypeError: <lambda>() takes 1 positional argument but 3 were given
```

The issue would seem to be with the `for_each()` method making the call `f(child, p, i)` against the `lambda node: node.check()`. Extra args are ignored in Javascript, but in Python this won't fly.

**Comment by elgow** [comment]
BTW, thank you for this Python version of ProseMirror. Trying to use the Javascript editor inside of  Python server code is miserable. 

I have found one trick that helps with using prosemirror-py. It's essential to scrub your schema of any Javascript code elements. I do this by using quickjs in the server to load my schema and then do a `JSON.stringify()` on it. This yields a JSON doc of all of the data elements of the schema present but all of the code elements stripped out.

**Comment by elgow** [comment]
Changing line 242 of prosemirror/model/node.py as below will fix it 
```
        return self.content.for_each(lambda node, *args: node.check())
```

**Comment by sciyoshi** [comment]
This is amazing @elgow - thank you for the contribution and the detailed bug report!
